//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCodeBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bicyclette
    {
        public int bicycletteId { get; set; }
        public string description { get; set; }
        public string rating { get; set; }
        public string price { get; set; }
        public string qty { get; set; }
        public string type { get; set; }
    }
}
